// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIH6OhsOVii4RoDUO9l_oiiE12HaH-xQ',
    appId: '1:931356082264:web:31b4cfd22de20ca07eca2d',
    messagingSenderId: '931356082264',
    projectId: 'share-ride-f71cd',
    authDomain: 'share-ride-f71cd.firebaseapp.com',
    storageBucket: 'share-ride-f71cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIAaETysGOpH7escuCll3GGkn9q9N1Pjc',
    appId: '1:931356082264:android:56ee6d4336de18a77eca2d',
    messagingSenderId: '931356082264',
    projectId: 'share-ride-f71cd',
    storageBucket: 'share-ride-f71cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAB8Bx8-wFPFyg3WyjKn2trFNOJsvfPdE',
    appId: '1:931356082264:ios:a85452601d507cec7eca2d',
    messagingSenderId: '931356082264',
    projectId: 'share-ride-f71cd',
    storageBucket: 'share-ride-f71cd.appspot.com',
    iosBundleId: 'com.shareride.shareride',
  );
}
